### ISSUE TITLE
Add support for isGroupRow

### ISSUE THREAD

**Issue by brendand** [brendand/mbtablegrid#17]
NSTableView has an isGroupRow delegate which returns a BOOL if the current row should span across all columns and be drawn using a different style than the rest of the rows.

For example:

    - (BOOL)tableView:(NSTableView *)tableView isGroupRow:(NSInteger)row {
	    BOOL isGroupRow = NO;
        // do something to determine from your model if the current row
        // is a section header (or group row)
	    return isGroupRow;
    }

It should also prevent selecting of cells in isGroupRow rows.

![screen shot 2014-11-03 at 10 20 38 pm](https://cloud.githubusercontent.com/assets/586075/4895145/601f76f6-63e2-11e4-888b-40446907c818.png)

**Comment by brendand** [comment]
Updated the sample app so row 0 and row 5 are designated as group rows. Just randomly picked those values.

**Comment by Dejal** [comment]
Might want to consider supporting floating group rows.  (See `-addFloatingSubview:forAxis:`.)  Probably not trivial, though.
