### ISSUE TITLE
The quick view icon and fill dot should only be visible on hover

### ISSUE THREAD

**Issue by Dejal** [brendand/mbtablegrid#33]
Having the quick view icon always visible adds clutter to the view, and it's really unattractive when there's a multiple selection:

![150227 multiple selection](https://cloud.githubusercontent.com/assets/1318849/6425023/e18fd46a-bec8-11e4-8202-af11b5fe819d.png)

So it'd be nicer if it only appeared when mousing over a cell.

Similarly, the fill down dot would be tidier if it only appeared when mousing over (as Numbers does).

**Comment by brendand** [comment]
Agreed.

**Comment by Dejal** [comment]
This is done, though the quick view hover thing is a little pointless, since clicking the quick view button will change to a single selection.  You should decide if either (a) the selection shouldn't change when it is clicked, or (b) it should, and thus should only show the quick view button when there is a single selection.  The former would be a new issue.

**Comment by brendand** [comment]
The way it works in Bento is when you click on a row, all the accessory view icons appear just for that row. Selecting multiple rows will actually show you all the accessory rows.

multiple selections:
![screen shot 2015-03-05 at 10 49 08 pm](https://cloud.githubusercontent.com/assets/586075/6520817/15884d04-c38a-11e4-8695-bcd35497bdf5.png)

single row selected:

![screen shot 2015-03-05 at 10 53 38 pm](https://cloud.githubusercontent.com/assets/586075/6520856/9a458cdc-c38a-11e4-8113-3429161db41c.png)

**Comment by brendand** [comment]
I notice there's a delay with the grab handle jumping to the top or bottom of the first or last cell depending on how you're dragging. Any way to tighten that redraw timing up?

**Comment by brendand** [comment]
P.S. :heart: the cell shading on the fill function.

**Comment by Dejal** [comment]
Selection: I could do that, but I personally think that having lots of accessory buttons visible is ugly (we don't need to clone Bento's approach).  Also, that doesn't address my question: clicking will always change the selection, so I was asking if clicking a button should work without changing the selection, or only show the button when there's a single selection, since that's effectively how it works now.

Re the delay, I could see if I can improve that.  It's due to the tracking areas and redrawing lagging behind the dragging (so making it faster might slow down dragging).

**Comment by brendand** [comment]
Hmm... I agree that having all those accessory buttons is ugly. I do like the idea of showing all the accessory buttons in every cell within the same row though. It lets the user know there are accessory buttons in other cells. I agree that we don't have to show every accessory button like Bento does during multiple selection. In fact, I don't think any accessory buttons should show during multiple row selection.

**Comment by Dejal** [comment]
Okay, I can change it to not show any accessory buttons when multiple cells are selected (which solves the issue of clicking changing the selection), and also to show all accessory buttons in the row of the selected cell.

**Comment by Dejal** [comment]
Done.  That simplified the table grid logic (don't need a tracking area for the accessory buttons).  I also moved the decision on when to display the accessory buttons to the controller, since it already has some logic there.  (In `-tableGrid:accessoryButtonImageForColumn:row:`).

**Comment by brendand** [comment]
:+1:
