### ISSUE TITLE
Moving columns doesn't work

### ISSUE THREAD

**Issue by Dejal** [brendand/mbtablegrid#34]
Dragging a column to move it looks like it's going to work, but the column doesn't actually move.

This might take a bit of work, as columns are accessed by index.  I notice that there is an unused column index property, presumably intended to map the actual column to the data model order.

Though I think it'd be a more elegant design to change the data source to use identifiers for the columns (like table views do), instead of fixed indexes.

**Comment by brendand** [comment]
:+1:
