### ISSUE TITLE
Redraw and cursor flicker issue when resizing columns

### ISSUE THREAD

**Issue by brendand** [brendand/mbtablegrid#42]
When you resize a column, the cursor is flickering, the sort indicator overlaps the header title, and the column divider jumps. The cursor is also misaligned with the divider line as it's being dragged. The flickering cursor doesn't really show in the video. But it flickers between the resizing cursor and the regular arrow cursor.

 See video:

![Column Resize Issue](https://dl.dropboxusercontent.com/s/3p50zzcpfv5pvqq/Jeff%20Recording%20-%20Mar%2010%2C%202015%2C%209.29.30.71%20PM.gif?dl=0)

**Comment by Dejal** [comment]
Yeah, I noticed that.  The jumping seemed to be related to increasing the minimum column width; something odd going on there.

**Comment by Dejal** [comment]
Done.  As a bonus, the cursor now changes to the right-only sizing one when the minimum is reached.

**Comment by brendand** [comment]
:+1:

**Comment by brendand** [comment]
There's still some resizing issues with the columns. If you drag a few columns to be really wide, then drag a column to the left to resize it to the minimum size, it will jump wide again. It makes it very difficult to resize the columns.

![Column Resize Issue](https://dl.dropboxusercontent.com/s/ot23dnw17umluxe/Jeff%20Recording%20-%20Mar%2021%2C%202015%2C%202.26.21.38%20AM.gif?dl=0)

**Comment by brendand** [comment]
Further to resizing columns, when you wiggle a column back and forth, the contentView frame keeps getting wider and wider. You can see it because the group rows are sized to the width of the contentView. So they appear to grow as the width of the contentView grows. It doesn't shrink back down when you drag left.

Somewhere here in MBTableGrid.m may be the culprit:

```
    if (currentWidth == minColumnWidth) {
        offset = columnRect.origin.x - location.x + minColumnWidth - self.rowHeaderView.frame.size.width;
        distance = 0.0;
    }
    
    // Update views with new sizes
    [contentView setFrameSize:NSMakeSize(NSWidth(contentView.frame) + distance, NSHeight(contentView.frame))];
```

**Comment by Dejal** [comment]
Both fixed.  The latter issue was a bit tricky to trace, but I got there.

**Comment by brendand** [comment]
:+1:
