### ISSUE TITLE
Add undo/redo support

### ISSUE THREAD

**Issue by brendand** [brendand/mbtablegrid#44]
If you fill up or down, you can easily lose data. Especially if you meant to simply select the rows but you accidentally initiated the fill command. So we need to be able to keep track of all the previous values and call tableGrid:setObjectValue:forColumn:row if the user uses the Undo command. The same goes for adding or deleting rows.

**Comment by Dejal** [comment]
Done basic undo/redo support.

It now supports Undo and Redo for all situations that edit cells (e.g. entering values, toggling checkboxes, etc), in addition to filling.

Not perfect; the selected cell isn't changed when undoing, like Numbers does.  And if rows are added during a fill, they aren't removed when undoing the fill.  I could see if I can make those enhancements if you wish.

**Comment by brendand** [comment]
Yes, removing any added rows would be helpful. And also re-adding any rows if you redo. The biggest issue to be handled was for filling because that can cause data loss if you accidentally fill down when you just meant to drag/select a bunch of cells. Great stuff!

**Comment by Dejal** [comment]
Done; it will now remove any added rows when undoing the fill, and re-add them when redoing.  It also adjusts the selection to match undoing/redoing the fill, like in Numbers.

**Comment by brendand** [comment]
:+1:
